### ISSUE TITLE
Add a note in readme to run install command as root

### ISSUE THREAD

**Issue by sitaramshelke** [martellaj/commemoji#1]
```
    $ npm install -g commemoji    
```

needs to be run as root. Add this in readme. :+1:  Emojis are fun. :smiley_cat:

**Comment by martellaj** [comment]
I think that depends on how you're set up on your system. [You shouldn't, and don't need to, do that.](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) Glad you like the project though! :dizzy:
